# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tff < Formula
  desc "Command-line interface for the FeedFactory API"
  homepage "https://github.com/TheFeedFactory/tff-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.1.0/tff-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "9ee42b7ddf60ebe1fdd938acbdca366b65ee1cbdd3617be2bffa6e7d6ae79325"

      def install
        bin.install "tff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.1.0/tff-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "56c55f97622b24daa797ef5d35d0a155314d2f5dd1975f9498509f71b2b03696"

      def install
        bin.install "tff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.1.0/tff-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "d69a0a8d22a4db41c567d6211451a264e342d9420a3c66271b5b6f153574b973"
      def install
        bin.install "tff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.1.0/tff-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "40558bf355b0a83fcad82133698653dcb38176dbbeb63b8f1ccb89db853e12ff"
      def install
        bin.install "tff"
      end
    end
  end

  test do
    system "#{bin}/tff", "--version"
  end
end
