# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tff < Formula
  desc "Command-line interface for the FeedFactory API"
  homepage "https://github.com/TheFeedFactory/tff-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.2.0/tff-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "054ca105d289eeeb53aba423fea861ed7f4d10a95f89de9e694e51880d4a940f"

      def install
        bin.install "tff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.2.0/tff-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "4c388d5ffaac4695fd3f1842875e2cc11bf8ae12243554c0437d76825bd1d022"

      def install
        bin.install "tff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.2.0/tff-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "a7eeefcc360640c1d5bdb90e4dbfb1002381051d99da2f2a9bab9259bee449f7"
      def install
        bin.install "tff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheFeedFactory/tff-cli/releases/download/v0.2.0/tff-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "0cb30b3ff7d32c20c991251b51075a5bd6ba5d5d0d7f5e5a6f844336ee40d3f3"
      def install
        bin.install "tff"
      end
    end
  end

  test do
    system "#{bin}/tff", "--version"
  end
end
